import Allison from './Allison'
import Barry from './Barry'
import Chantal from './Chantal'
import Dean from './Dean'
import Erin from './Erin'
import Unnamed_6 from './Unnamed_6'
import Felix from './Felix'
import Gabrielle from './Gabrielle'
import Humberto from './Humberto'
import Iris from './Iris'
import Jerry from './Jerry'
import Karen from './Karen'
import Luis from './Luis'
import Unnamed_14 from './Unnamed_14'
import Marilyn from './Marilyn'
import Noel from './Noel'
import Opal from './Opal'
import Pablo from './Pablo'
import Roxanne from './Roxanne'
import Sebastien from './Sebastien'
import Tanya from './Tanya'

const hurdat2_1995 = [Allison, Barry, Chantal, Dean, Erin, Unnamed_6, Felix, Gabrielle, Humberto, Iris, Jerry, Karen, Luis, Unnamed_14, Marilyn, Noel, Opal, Pablo, Roxanne, Sebastien, Tanya]

export default hurdat2_1995