const HUMBERTO = [
  {
    "date": "20130908",
    "time_utc": " 0000",
    "record": "  ",
    "status": " LO",
    "lat": " 13.0N",
    "lng": "  17.6W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1009",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130908",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 13.0N",
    "lng": "  18.4W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1009",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130908",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 13.0N",
    "lng": "  19.3W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1009",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130908",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TD",
    "lat": " 13.0N",
    "lng": "  20.3W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1008",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130909",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TD",
    "lat": " 13.1N",
    "lng": "  21.3W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130909",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 13.3N",
    "lng": "  22.4W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130909",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 13.5N",
    "lng": "  23.6W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130909",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 13.7N",
    "lng": "  24.6W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "   80",
    "34kt_wind_radius_nm_se": "   40",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130910",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 13.9N",
    "lng": "  25.5W",
    "max_wind_kt": "  50",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   90",
    "34kt_wind_radius_nm_se": "   60",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   30",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130910",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 14.1N",
    "lng": "  26.5W",
    "max_wind_kt": "  55",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "   80",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   30",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130910",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 14.3N",
    "lng": "  27.3W",
    "max_wind_kt": "  55",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "   80",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   30",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   30",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130910",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 14.7N",
    "lng": "  27.9W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  999",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "   80",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   30",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   30",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130911",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 15.1N",
    "lng": "  28.3W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  998",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   90",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130911",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 15.6N",
    "lng": "  28.6W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   90",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130911",
    "time_utc": " 1200",
    "record": "  ",
    "status": " HU",
    "lat": " 16.3N",
    "lng": "  28.9W",
    "max_wind_kt": "  70",
    "min_pressure_mb": "  987",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   90",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "   30",
    "64kt_wind_radius_nm_se": "   20",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130911",
    "time_utc": " 1800",
    "record": "  ",
    "status": " HU",
    "lat": " 17.4N",
    "lng": "  28.9W",
    "max_wind_kt": "  80",
    "min_pressure_mb": "  979",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   90",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "   30",
    "64kt_wind_radius_nm_se": "   20",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "   20",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130912",
    "time_utc": " 0000",
    "record": "  ",
    "status": " HU",
    "lat": " 18.6N",
    "lng": "  28.9W",
    "max_wind_kt": "  80",
    "min_pressure_mb": "  979",
    "34kt_wind_radius_nm_ne": "  130",
    "34kt_wind_radius_nm_se": "  120",
    "34kt_wind_radius_nm_nw": "   70",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   50",
    "64kt_wind_radius_nm_ne": "   40",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   20",
    "64kt_wind_radius_nm_sw": "   30",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130912",
    "time_utc": " 0600",
    "record": "  ",
    "status": " HU",
    "lat": " 19.9N",
    "lng": "  28.9W",
    "max_wind_kt": "  80",
    "min_pressure_mb": "  979",
    "34kt_wind_radius_nm_ne": "  140",
    "34kt_wind_radius_nm_se": "  130",
    "34kt_wind_radius_nm_nw": "   70",
    "34kt_wind_radius_nm_sw": "  130",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "   30",
    "50kt_wind_radius_nm_sw": "   50",
    "64kt_wind_radius_nm_ne": "   40",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   20",
    "64kt_wind_radius_nm_sw": "   30",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130912",
    "time_utc": " 1200",
    "record": "  ",
    "status": " HU",
    "lat": " 21.2N",
    "lng": "  28.9W",
    "max_wind_kt": "  75",
    "min_pressure_mb": "  980",
    "34kt_wind_radius_nm_ne": "  150",
    "34kt_wind_radius_nm_se": "  140",
    "34kt_wind_radius_nm_nw": "   70",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   50",
    "64kt_wind_radius_nm_ne": "   40",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   20",
    "64kt_wind_radius_nm_sw": "   30",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130912",
    "time_utc": " 1800",
    "record": "  ",
    "status": " HU",
    "lat": " 22.3N",
    "lng": "  29.1W",
    "max_wind_kt": "  75",
    "min_pressure_mb": "  980",
    "34kt_wind_radius_nm_ne": "  160",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "   70",
    "50kt_wind_radius_nm_se": "   60",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   60",
    "64kt_wind_radius_nm_ne": "   40",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   20",
    "64kt_wind_radius_nm_sw": "   30",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130913",
    "time_utc": " 0000",
    "record": "  ",
    "status": " HU",
    "lat": " 23.2N",
    "lng": "  29.5W",
    "max_wind_kt": "  70",
    "min_pressure_mb": "  982",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "  160",
    "34kt_wind_radius_nm_nw": "   90",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "   80",
    "50kt_wind_radius_nm_se": "   60",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   60",
    "64kt_wind_radius_nm_ne": "   40",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   20",
    "64kt_wind_radius_nm_sw": "   30",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130913",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 24.0N",
    "lng": "  30.0W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  986",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "  160",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "   90",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   50",
    "50kt_wind_radius_nm_sw": "   70",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130913",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 24.6N",
    "lng": "  30.8W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  988",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "  160",
    "34kt_wind_radius_nm_nw": "  110",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "   90",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   50",
    "50kt_wind_radius_nm_sw": "   70",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130913",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 24.8N",
    "lng": "  31.7W",
    "max_wind_kt": "  45",
    "min_pressure_mb": "  995",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "  140",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  160",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130914",
    "time_utc": " 0000",
    "record": "  ",
    "status": " LO",
    "lat": " 24.8N",
    "lng": "  32.6W",
    "max_wind_kt": "  40",
    "min_pressure_mb": "  999",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "  120",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "  140",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130914",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 24.9N",
    "lng": "  33.6W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1003",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130914",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 25.2N",
    "lng": "  34.8W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130914",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 25.5N",
    "lng": "  36.3W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130915",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 25.6N",
    "lng": "  37.8W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130915",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 25.6N",
    "lng": "  38.9W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  190",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130915",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 25.9N",
    "lng": "  39.7W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130915",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 26.4N",
    "lng": "  40.4W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130916",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 26.7N",
    "lng": "  41.3W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  120",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130916",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 26.7N",
    "lng": "  42.4W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  190",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  110",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130916",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 26.8N",
    "lng": "  42.9W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  180",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130916",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 26.9N",
    "lng": "  43.3W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  170",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   90",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130917",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 27.0N",
    "lng": "  43.2W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "  160",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130917",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 27.4N",
    "lng": "  42.9W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "  140",
    "34kt_wind_radius_nm_se": "  120",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130917",
    "time_utc": " 1200",
    "record": "  ",
    "status": " SS",
    "lat": " 28.4N",
    "lng": "  42.6W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  120",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130917",
    "time_utc": " 1800",
    "record": "  ",
    "status": " SS",
    "lat": " 29.5N",
    "lng": "  42.7W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130918",
    "time_utc": " 0000",
    "record": "  ",
    "status": " SS",
    "lat": " 30.5N",
    "lng": "  43.2W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1003",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130918",
    "time_utc": " 0600",
    "record": "  ",
    "status": " SD",
    "lat": " 31.1N",
    "lng": "  43.6W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130918",
    "time_utc": " 1200",
    "record": "  ",
    "status": " SD",
    "lat": " 31.6N",
    "lng": "  43.9W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130918",
    "time_utc": " 1800",
    "record": "  ",
    "status": " SD",
    "lat": " 32.0N",
    "lng": "  44.1W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130919",
    "time_utc": " 0000",
    "record": "  ",
    "status": " SD",
    "lat": " 32.5N",
    "lng": "  44.3W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20130919",
    "time_utc": " 0600",
    "record": "  ",
    "status": " SD",
    "lat": " 33.0N",
    "lng": "  44.5W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  }
]
export default HUMBERTO