import Unnamed_1 from './Unnamed_1'
import Unnamed_2 from './Unnamed_2'
import Unnamed_3 from './Unnamed_3'
import Unnamed_4 from './Unnamed_4'
import Unnamed_5 from './Unnamed_5'
import Unnamed_6 from './Unnamed_6'
import Alma from './Alma'
import Unnamed_8 from './Unnamed_8'
import Becky from './Becky'
import Carmen from './Carmen'
import Unnamed_11 from './Unnamed_11'
import Dolly from './Dolly'
import Elaine from './Elaine'
import Fifi from './Fifi'
import Unnamed_15 from './Unnamed_15'
import Unnamed_16 from './Unnamed_16'
import Gertrude from './Gertrude'
import Unnamed_18 from './Unnamed_18'
import Unnamed_19 from './Unnamed_19'
import Unnamed_20 from './Unnamed_20'

const hurdat2_1974 = [Unnamed_1, Unnamed_2, Unnamed_3, Unnamed_4, Unnamed_5, Unnamed_6, Alma, Unnamed_8, Becky, Carmen, Unnamed_11, Dolly, Elaine, Fifi, Unnamed_15, Unnamed_16, Gertrude, Unnamed_18, Unnamed_19, Unnamed_20]

export default hurdat2_1974import Unnamed_1 from './Unnamed_1'
import Unnamed_2 from './Unnamed_2'
import Unnamed_3 from './Unnamed_3'
import Unnamed_4 from './Unnamed_4'
import Unnamed_5 from './Unnamed_5'
import Unnamed_6 from './Unnamed_6'
import Alma from './Alma'
import Unnamed_8 from './Unnamed_8'
import Becky from './Becky'
import Carmen from './Carmen'
import Unnamed_11 from './Unnamed_11'
import Dolly from './Dolly'
import Elaine from './Elaine'
import Fifi from './Fifi'
import Unnamed_15 from './Unnamed_15'
import Unnamed_16 from './Unnamed_16'
import Gertrude from './Gertrude'
import Unnamed_18 from './Unnamed_18'
import Unnamed_19 from './Unnamed_19'
import Unnamed_20 from './Unnamed_20'

const hurdat2_1974 = [Unnamed_1, Unnamed_2, Unnamed_3, Unnamed_4, Unnamed_5, Unnamed_6, Alma, Unnamed_8, Becky, Carmen, Unnamed_11, Dolly, Elaine, Fifi, Unnamed_15, Unnamed_16, Gertrude, Unnamed_18, Unnamed_19, Unnamed_20]

export default hurdat2_1974