const Gert = [
  {
    "date": "20050723",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TD",
    "lat": " 19.3N",
    "lng": "  92.9W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1011",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050724",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TD",
    "lat": " 19.8N",
    "lng": "  93.8W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1009",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050724",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 20.8N",
    "lng": "  95.0W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1009",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050724",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 21.0N",
    "lng": "  95.8W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1008",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "   50",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050724",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 21.4N",
    "lng": "  96.6W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "   75",
    "34kt_wind_radius_nm_sw": "   75",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050725",
    "time_utc": " 0000",
    "record": " L",
    "status": " TS",
    "lat": " 21.8N",
    "lng": "  97.6W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   75",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050725",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TD",
    "lat": " 22.3N",
    "lng": "  98.6W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050725",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TD",
    "lat": " 22.5N",
    "lng": " 100.0W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20050725",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 22.5N",
    "lng": " 101.4W",
    "max_wind_kt": "  20",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  }
]
export default Gert