import ARLENE from './ARLENE'
import BRET from './BRET'
import CINDY from './CINDY'
import DENNIS from './DENNIS'
import EMILY from './EMILY'
import FRANKLIN from './FRANKLIN'
import GERT from './GERT'
import HARVEY from './HARVEY'
import IRENE from './IRENE'
import TEN from './TEN'
import JOSE from './JOSE'
import KATRINA from './KATRINA'
import LEE from './LEE'
import MARIA from './MARIA'
import NATE from './NATE'
import OPHELIA from './OPHELIA'
import PHILIPPE from './PHILIPPE'
import RITA from './RITA'
import NINETEEN from './NINETEEN'
import STAN from './STAN'
import UNNAMED_21 from './UNNAMED_21'
import TAMMY from './TAMMY'
import TWENTY-TWO from './TWENTY-TWO'
import VINCE from './VINCE'
import WILMA from './WILMA'
import ALPHA from './ALPHA'
import BETA from './BETA'
import GAMMA from './GAMMA'
import DELTA from './DELTA'
import EPSILON from './EPSILON'
import ZETA from './ZETA'

const hurdat2_2005 = [ARLENE, BRET, CINDY, DENNIS, EMILY, FRANKLIN, GERT, HARVEY, IRENE, TEN, JOSE, KATRINA, LEE, MARIA, NATE, OPHELIA, PHILIPPE, RITA, NINETEEN, STAN, UNNAMED_21, TAMMY, TWENTY-TWO, VINCE, WILMA, ALPHA, BETA, GAMMA, DELTA, EPSILON, ZETA]

export default hurdat2_2005