const Lisa = [
  {
    "date": "20040919",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TD",
    "lat": " 13.3N",
    "lng": "  32.4W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040920",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TD",
    "lat": " 13.3N",
    "lng": "  33.3W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040920",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TD",
    "lat": " 13.4N",
    "lng": "  34.3W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040920",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 13.5N",
    "lng": "  35.4W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   40",
    "34kt_wind_radius_nm_se": "   40",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040920",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 13.7N",
    "lng": "  36.4W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "   45",
    "34kt_wind_radius_nm_se": "   45",
    "34kt_wind_radius_nm_nw": "   45",
    "34kt_wind_radius_nm_sw": "   45",
    "50kt_wind_radius_nm_ne": "   15",
    "50kt_wind_radius_nm_se": "   15",
    "50kt_wind_radius_nm_nw": "   15",
    "50kt_wind_radius_nm_sw": "   15",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040921",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 13.7N",
    "lng": "  37.4W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "   45",
    "34kt_wind_radius_nm_se": "   45",
    "34kt_wind_radius_nm_nw": "   45",
    "34kt_wind_radius_nm_sw": "   45",
    "50kt_wind_radius_nm_ne": "   15",
    "50kt_wind_radius_nm_se": "   15",
    "50kt_wind_radius_nm_nw": "   15",
    "50kt_wind_radius_nm_sw": "   15",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040921",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 13.9N",
    "lng": "  38.3W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   45",
    "34kt_wind_radius_nm_se": "   45",
    "34kt_wind_radius_nm_nw": "   45",
    "34kt_wind_radius_nm_sw": "   45",
    "50kt_wind_radius_nm_ne": "   15",
    "50kt_wind_radius_nm_se": "   15",
    "50kt_wind_radius_nm_nw": "   15",
    "50kt_wind_radius_nm_sw": "   15",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040921",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 14.1N",
    "lng": "  39.1W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   45",
    "34kt_wind_radius_nm_se": "   45",
    "34kt_wind_radius_nm_nw": "   45",
    "34kt_wind_radius_nm_sw": "   45",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040921",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 14.3N",
    "lng": "  39.7W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   45",
    "34kt_wind_radius_nm_se": "   45",
    "34kt_wind_radius_nm_nw": "   45",
    "34kt_wind_radius_nm_sw": "   45",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040922",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 14.4N",
    "lng": "  40.2W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "   50",
    "34kt_wind_radius_nm_nw": "   30",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040922",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 14.4N",
    "lng": "  40.6W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "   50",
    "34kt_wind_radius_nm_nw": "   30",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040922",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 14.2N",
    "lng": "  41.1W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   40",
    "34kt_wind_radius_nm_se": "   40",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040922",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 13.9N",
    "lng": "  41.5W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   40",
    "34kt_wind_radius_nm_se": "   40",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040923",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 13.2N",
    "lng": "  41.4W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   40",
    "34kt_wind_radius_nm_se": "   40",
    "34kt_wind_radius_nm_nw": "   40",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040923",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 13.0N",
    "lng": "  40.6W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "   50",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040923",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 13.1N",
    "lng": "  40.0W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1003",
    "34kt_wind_radius_nm_ne": "   50",
    "34kt_wind_radius_nm_se": "   50",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040923",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TD",
    "lat": " 14.3N",
    "lng": "  40.5W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040924",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TD",
    "lat": " 14.3N",
    "lng": "  41.7W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040924",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 13.8N",
    "lng": "  42.4W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "   60",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040924",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 13.9N",
    "lng": "  43.2W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1003",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "   60",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040924",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TD",
    "lat": " 14.0N",
    "lng": "  43.8W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040925",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TD",
    "lat": " 14.3N",
    "lng": "  44.4W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040925",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 14.9N",
    "lng": "  44.9W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1003",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040925",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 15.7N",
    "lng": "  45.4W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040925",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 16.7N",
    "lng": "  45.7W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040926",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 17.4N",
    "lng": "  45.8W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040926",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 18.0N",
    "lng": "  45.9W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040926",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 18.7N",
    "lng": "  46.0W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040926",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 19.2N",
    "lng": "  46.0W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   50",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   20",
    "50kt_wind_radius_nm_se": "   20",
    "50kt_wind_radius_nm_nw": "   20",
    "50kt_wind_radius_nm_sw": "   20",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040927",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 19.6N",
    "lng": "  46.0W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   25",
    "34kt_wind_radius_nm_sw": "   75",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040927",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 20.0N",
    "lng": "  46.1W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040927",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 20.6N",
    "lng": "  46.2W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040927",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 21.3N",
    "lng": "  46.2W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   60",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040928",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 22.0N",
    "lng": "  46.4W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040928",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 23.0N",
    "lng": "  46.5W",
    "max_wind_kt": "  40",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "   90",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040928",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 24.3N",
    "lng": "  46.5W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "   90",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040928",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 25.4N",
    "lng": "  46.5W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "   75",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "   50",
    "50kt_wind_radius_nm_ne": "   30",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   30",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040929",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 26.4N",
    "lng": "  46.4W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  125",
    "34kt_wind_radius_nm_se": "   75",
    "34kt_wind_radius_nm_nw": "   25",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   30",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   30",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040929",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 27.5N",
    "lng": "  46.2W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  175",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   75",
    "34kt_wind_radius_nm_sw": "   75",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   30",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040929",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 28.9N",
    "lng": "  45.8W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  175",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "   60",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040929",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 30.1N",
    "lng": "  45.8W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  175",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040930",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 31.1N",
    "lng": "  46.1W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "  200",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  150",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040930",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 32.0N",
    "lng": "  46.7W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "  200",
    "34kt_wind_radius_nm_se": "  200",
    "34kt_wind_radius_nm_nw": "  100",
    "34kt_wind_radius_nm_sw": "  150",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040930",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 32.4N",
    "lng": "  47.3W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "  150",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20040930",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 33.1N",
    "lng": "  47.8W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "  125",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041001",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 34.1N",
    "lng": "  47.8W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "  125",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041001",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 35.1N",
    "lng": "  47.6W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "  125",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "   40",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041001",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 36.3N",
    "lng": "  47.0W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   90",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041001",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 37.7N",
    "lng": "  45.8W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041002",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 38.9N",
    "lng": "  43.8W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041002",
    "time_utc": " 0600",
    "record": "  ",
    "status": " HU",
    "lat": " 40.3N",
    "lng": "  41.6W",
    "max_wind_kt": "  65",
    "min_pressure_mb": "  987",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   20",
    "64kt_wind_radius_nm_se": "   20",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041002",
    "time_utc": " 1200",
    "record": "  ",
    "status": " HU",
    "lat": " 41.6N",
    "lng": "  39.1W",
    "max_wind_kt": "  65",
    "min_pressure_mb": "  987",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "   90",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   40",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   20",
    "64kt_wind_radius_nm_se": "   20",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041002",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 42.8N",
    "lng": "  36.0W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041003",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 43.8N",
    "lng": "  33.0W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  997",
    "34kt_wind_radius_nm_ne": "   60",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20041003",
    "time_utc": " 0600",
    "record": "  ",
    "status": " EX",
    "lat": " 44.5N",
    "lng": "  30.0W",
    "max_wind_kt": "  45",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "  125",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  }
]
export default Lisa