import Unnamed_1 from './Unnamed_1'
import Unnamed_2 from './Unnamed_2'
import Anna from './Anna'
import Blanche from './Blanche'
import Debbie from './Debbie'
import Camille from './Camille'
import Eve from './Eve'
import Francelia from './Francelia'
import Unnamed_9 from './Unnamed_9'
import Gerda from './Gerda'
import Holly from './Holly'
import Unnamed_12 from './Unnamed_12'
import Inga from './Inga'
import Unnamed_14 from './Unnamed_14'
import Unnamed_15 from './Unnamed_15'
import Unnamed_16 from './Unnamed_16'
import Jenny from './Jenny'
import Kara from './Kara'
import Laurie from './Laurie'
import Unnamed_20 from './Unnamed_20'
import Unnamed_21 from './Unnamed_21'
import Martha from './Martha'
import Unnamed_23 from './Unnamed_23'

const hurdat2_1969 = [Unnamed_1, Unnamed_2, Anna, Blanche, Debbie, Camille, Eve, Francelia, Unnamed_9, Gerda, Holly, Unnamed_12, Inga, Unnamed_14, Unnamed_15, Unnamed_16, Jenny, Kara, Laurie, Unnamed_20, Unnamed_21, Martha, Unnamed_23]

export default hurdat2_1969