const OTTO = [
  {
    "date": "20101006",
    "time_utc": " 0600",
    "record": "  ",
    "status": " SD",
    "lat": " 22.0N",
    "lng": "  67.2W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1000",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101006",
    "time_utc": " 1200",
    "record": "  ",
    "status": " SS",
    "lat": " 22.6N",
    "lng": "  67.8W",
    "max_wind_kt": "  40",
    "min_pressure_mb": "  995",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101006",
    "time_utc": " 1800",
    "record": "  ",
    "status": " SS",
    "lat": " 23.0N",
    "lng": "  68.1W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  991",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101007",
    "time_utc": " 0000",
    "record": "  ",
    "status": " SS",
    "lat": " 23.2N",
    "lng": "  68.2W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  989",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101007",
    "time_utc": " 0600",
    "record": "  ",
    "status": " SS",
    "lat": " 23.4N",
    "lng": "  68.3W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  990",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101007",
    "time_utc": " 1200",
    "record": "  ",
    "status": " TS",
    "lat": " 23.6N",
    "lng": "  68.3W",
    "max_wind_kt": "  45",
    "min_pressure_mb": "  994",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101007",
    "time_utc": " 1800",
    "record": "  ",
    "status": " TS",
    "lat": " 23.8N",
    "lng": "  67.8W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  992",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  120",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   30",
    "50kt_wind_radius_nm_se": "   30",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101008",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 24.0N",
    "lng": "  67.0W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  989",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101008",
    "time_utc": " 0600",
    "record": "  ",
    "status": " TS",
    "lat": " 24.4N",
    "lng": "  66.1W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  986",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   40",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101008",
    "time_utc": " 1200",
    "record": "  ",
    "status": " HU",
    "lat": " 25.2N",
    "lng": "  64.8W",
    "max_wind_kt": "  65",
    "min_pressure_mb": "  983",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  170",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   50",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   20",
    "64kt_wind_radius_nm_se": "   25",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101008",
    "time_utc": " 1800",
    "record": "  ",
    "status": " HU",
    "lat": " 26.2N",
    "lng": "  63.3W",
    "max_wind_kt": "  70",
    "min_pressure_mb": "  980",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  170",
    "34kt_wind_radius_nm_nw": "   80",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   60",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   20",
    "64kt_wind_radius_nm_se": "   25",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101009",
    "time_utc": " 0000",
    "record": "  ",
    "status": " HU",
    "lat": " 27.2N",
    "lng": "  61.7W",
    "max_wind_kt": "  75",
    "min_pressure_mb": "  976",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "  190",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   40",
    "50kt_wind_radius_nm_se": "   60",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   20",
    "64kt_wind_radius_nm_se": "   25",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101009",
    "time_utc": " 0600",
    "record": "  ",
    "status": " HU",
    "lat": " 28.5N",
    "lng": "  59.7W",
    "max_wind_kt": "  75",
    "min_pressure_mb": "  978",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "  190",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   25",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101009",
    "time_utc": " 1200",
    "record": "  ",
    "status": " HU",
    "lat": " 30.0N",
    "lng": "  57.3W",
    "max_wind_kt": "  70",
    "min_pressure_mb": "  981",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "  190",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   25",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101009",
    "time_utc": " 1800",
    "record": "  ",
    "status": " HU",
    "lat": " 31.4N",
    "lng": "  54.3W",
    "max_wind_kt": "  65",
    "min_pressure_mb": "  985",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "  190",
    "34kt_wind_radius_nm_nw": "   60",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "   25",
    "64kt_wind_radius_nm_se": "   30",
    "64kt_wind_radius_nm_nw": "   15",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101010",
    "time_utc": " 0000",
    "record": "  ",
    "status": " TS",
    "lat": " 32.7N",
    "lng": "  50.9W",
    "max_wind_kt": "  60",
    "min_pressure_mb": "  988",
    "34kt_wind_radius_nm_ne": "  110",
    "34kt_wind_radius_nm_se": "  190",
    "34kt_wind_radius_nm_nw": "   90",
    "34kt_wind_radius_nm_sw": "   70",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   70",
    "50kt_wind_radius_nm_nw": "   40",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101010",
    "time_utc": " 0600",
    "record": "  ",
    "status": " EX",
    "lat": " 34.3N",
    "lng": "  47.0W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  988",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  220",
    "34kt_wind_radius_nm_nw": "  120",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   90",
    "50kt_wind_radius_nm_nw": "   60",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101010",
    "time_utc": " 1200",
    "record": "  ",
    "status": " EX",
    "lat": " 36.4N",
    "lng": "  42.6W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  988",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  220",
    "34kt_wind_radius_nm_nw": "  120",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   90",
    "50kt_wind_radius_nm_nw": "   90",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101010",
    "time_utc": " 1800",
    "record": "  ",
    "status": " EX",
    "lat": " 38.2N",
    "lng": "  38.1W",
    "max_wind_kt": "  55",
    "min_pressure_mb": "  988",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  240",
    "34kt_wind_radius_nm_nw": "  180",
    "34kt_wind_radius_nm_sw": "   80",
    "50kt_wind_radius_nm_ne": "   50",
    "50kt_wind_radius_nm_se": "   90",
    "50kt_wind_radius_nm_nw": "   90",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101011",
    "time_utc": " 0000",
    "record": "  ",
    "status": " EX",
    "lat": " 40.3N",
    "lng": "  33.8W",
    "max_wind_kt": "  50",
    "min_pressure_mb": "  992",
    "34kt_wind_radius_nm_ne": "  120",
    "34kt_wind_radius_nm_se": "  240",
    "34kt_wind_radius_nm_nw": "  240",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "   90",
    "50kt_wind_radius_nm_nw": "  120",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101011",
    "time_utc": " 0600",
    "record": "  ",
    "status": " EX",
    "lat": " 42.0N",
    "lng": "  30.8W",
    "max_wind_kt": "  45",
    "min_pressure_mb": "  995",
    "34kt_wind_radius_nm_ne": "  150",
    "34kt_wind_radius_nm_se": "  200",
    "34kt_wind_radius_nm_nw": "  240",
    "34kt_wind_radius_nm_sw": "   60",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101011",
    "time_utc": " 1200",
    "record": "  ",
    "status": " EX",
    "lat": " 43.1N",
    "lng": "  28.1W",
    "max_wind_kt": "  40",
    "min_pressure_mb": "  998",
    "34kt_wind_radius_nm_ne": "  150",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "  240",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101011",
    "time_utc": " 1800",
    "record": "  ",
    "status": " EX",
    "lat": " 43.5N",
    "lng": "  26.3W",
    "max_wind_kt": "  40",
    "min_pressure_mb": "  998",
    "34kt_wind_radius_nm_ne": "  150",
    "34kt_wind_radius_nm_se": "  150",
    "34kt_wind_radius_nm_nw": "  240",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101012",
    "time_utc": " 0000",
    "record": "  ",
    "status": " EX",
    "lat": " 43.4N",
    "lng": "  25.3W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1002",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "  100",
    "34kt_wind_radius_nm_nw": "  200",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101012",
    "time_utc": " 0600",
    "record": "  ",
    "status": " EX",
    "lat": " 42.4N",
    "lng": "  24.6W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "  150",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101012",
    "time_utc": " 1200",
    "record": "  ",
    "status": " EX",
    "lat": " 41.4N",
    "lng": "  24.0W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "  100",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101012",
    "time_utc": " 1800",
    "record": "  ",
    "status": " EX",
    "lat": " 40.3N",
    "lng": "  23.5W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101013",
    "time_utc": " 0000",
    "record": "  ",
    "status": " EX",
    "lat": " 39.3N",
    "lng": "  23.0W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101013",
    "time_utc": " 0600",
    "record": "  ",
    "status": " EX",
    "lat": " 38.4N",
    "lng": "  22.7W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101013",
    "time_utc": " 1200",
    "record": "  ",
    "status": " EX",
    "lat": " 37.6N",
    "lng": "  22.6W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101013",
    "time_utc": " 1800",
    "record": "  ",
    "status": " EX",
    "lat": " 36.7N",
    "lng": "  22.4W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101014",
    "time_utc": " 0000",
    "record": "  ",
    "status": " EX",
    "lat": " 35.8N",
    "lng": "  22.2W",
    "max_wind_kt": "  35",
    "min_pressure_mb": " 1004",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "  100",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101014",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 35.0N",
    "lng": "  22.0W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101014",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 34.4N",
    "lng": "  21.4W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101014",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 34.0N",
    "lng": "  20.6W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1005",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101015",
    "time_utc": " 0000",
    "record": "  ",
    "status": " LO",
    "lat": " 33.8N",
    "lng": "  19.9W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101015",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 33.6N",
    "lng": "  19.2W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101015",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 33.4N",
    "lng": "  18.5W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101015",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 33.2N",
    "lng": "  17.8W",
    "max_wind_kt": "  30",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101016",
    "time_utc": " 0000",
    "record": "  ",
    "status": " LO",
    "lat": " 33.0N",
    "lng": "  17.1W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101016",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 32.8N",
    "lng": "  16.5W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1006",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101016",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 32.6N",
    "lng": "  15.9W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101016",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 32.4N",
    "lng": "  15.3W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1007",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101017",
    "time_utc": " 0000",
    "record": "  ",
    "status": " LO",
    "lat": " 32.3N",
    "lng": "  14.7W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1008",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101017",
    "time_utc": " 0600",
    "record": "  ",
    "status": " LO",
    "lat": " 32.1N",
    "lng": "  14.5W",
    "max_wind_kt": "  25",
    "min_pressure_mb": " 1010",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101017",
    "time_utc": " 1200",
    "record": "  ",
    "status": " LO",
    "lat": " 31.9N",
    "lng": "  14.6W",
    "max_wind_kt": "  20",
    "min_pressure_mb": " 1010",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  },
  {
    "date": "20101017",
    "time_utc": " 1800",
    "record": "  ",
    "status": " LO",
    "lat": " 31.7N",
    "lng": "  14.7W",
    "max_wind_kt": "  20",
    "min_pressure_mb": " 1012",
    "34kt_wind_radius_nm_ne": "    0",
    "34kt_wind_radius_nm_se": "    0",
    "34kt_wind_radius_nm_nw": "    0",
    "34kt_wind_radius_nm_sw": "    0",
    "50kt_wind_radius_nm_ne": "    0",
    "50kt_wind_radius_nm_se": "    0",
    "50kt_wind_radius_nm_nw": "    0",
    "50kt_wind_radius_nm_sw": "    0",
    "64kt_wind_radius_nm_ne": "    0",
    "64kt_wind_radius_nm_se": "    0",
    "64kt_wind_radius_nm_nw": "    0",
    "64kt_wind_radius_nm_sw": "    0",
    "max_wind_radius_nm": " -999"
  }
]
export default OTTO