import ALMA from './ALMA'
import BECKY from './BECKY'
import UNNAMED_3 from './UNNAMED_3'
import CELIA from './CELIA'
import UNNAMED_5 from './UNNAMED_5'
import UNNAMED_6 from './UNNAMED_6'
import UNNAMED_7 from './UNNAMED_7'
import DOROTHY from './DOROTHY'
import UNNAMED_9 from './UNNAMED_9'
import UNNAMED_10 from './UNNAMED_10'
import ELLA from './ELLA'
import FELICE from './FELICE'
import UNNAMED_13 from './UNNAMED_13'
import UNNAMED_14 from './UNNAMED_14'
import GRETA from './GRETA'
import UNNAMED_16 from './UNNAMED_16'
import UNNAMED_17 from './UNNAMED_17'
import UNNAMED_18 from './UNNAMED_18'
import UNNAMED_19 from './UNNAMED_19'
import UNNAMED_20 from './UNNAMED_20'
import UNNAMED_21 from './UNNAMED_21'

const hurdat2_1970 = [ALMA, BECKY, UNNAMED_3, CELIA, UNNAMED_5, UNNAMED_6, UNNAMED_7, DOROTHY, UNNAMED_9, UNNAMED_10, ELLA, FELICE, UNNAMED_13, UNNAMED_14, GRETA, UNNAMED_16, UNNAMED_17, UNNAMED_18, UNNAMED_19, UNNAMED_20, UNNAMED_21]

export default hurdat2_1970