import ARTHUR from './ARTHUR'
import BERTHA from './BERTHA'
import CRISTOBAL from './CRISTOBAL'
import DOLLY from './DOLLY'
import EDOUARD from './EDOUARD'
import FAY from './FAY'
import GONZALO from './GONZALO'
import HANNA from './HANNA'
import ISAIAS from './ISAIAS'
import TEN from './TEN'
import JOSEPHINE from './JOSEPHINE'
import KYLE from './KYLE'
import LAURA from './LAURA'
import MARCO from './MARCO'
import OMAR from './OMAR'
import NANA from './NANA'
import PAULETTE from './PAULETTE'
import RENE from './RENE'
import SALLY from './SALLY'
import TEDDY from './TEDDY'
import VICKY from './VICKY'
import BETA from './BETA'
import WILFRED from './WILFRED'
import ALPHA from './ALPHA'
import GAMMA from './GAMMA'
import DELTA from './DELTA'
import EPSILON from './EPSILON'
import ZETA from './ZETA'
import ETA from './ETA'
import THETA from './THETA'
import IOTA from './IOTA'

const hurdat2_2020 = [ARTHUR, BERTHA, CRISTOBAL, DOLLY, EDOUARD, FAY, GONZALO, HANNA, ISAIAS, TEN, JOSEPHINE, KYLE, LAURA, MARCO, OMAR, NANA, PAULETTE, RENE, SALLY, TEDDY, VICKY, BETA, WILFRED, ALPHA, GAMMA, DELTA, EPSILON, ZETA, ETA, THETA, IOTA]

export default hurdat2_2020